"""add

Revision ID: 62920d7233b5
Revises: 4fb3b0928607
Create Date: 2024-08-29 11:50:11.728886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62920d7233b5'
down_revision: Union[str, None] = '4fb3b0928607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'updated_at')
    op.add_column('reviews', sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'update_at')
    op.drop_column('reviews', 'review_text')
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'update_at')
    # ### end Alembic commands ###
